const assert=require('node:assert/strict'),R=require('./engine.js');
const p=(x,y)=>({x,y});let s=R.fresh();
let q=R.quote(s,'res',p(2.137,4.283),p(2.137,4.283));assert.equal(q.cells.length,1);assert.equal(q.cells[0].x,1.637);assert(Math.abs(q.cells[0].y-3.783)<1e-10);assert.equal(q.total,5075);
R.build(s,'res',p(2.137,4.283),p(2.137,4.283),()=>.99);assert.equal(s.money,94925);assert.equal(s.buildings[0].variant,2);
const before=JSON.stringify(s);assert.equal(R.build(s,'com',p(2.4,4.5),p(2.4,4.5)),false);assert.equal(JSON.stringify(s),before);
q=R.build(s,'com',p(3.09,4.283),p(3.09,4.283),()=>0);assert.equal(q.total,8200);assert(!R.overlaps(s.buildings[0],s.buildings[1]));assert(R.restore(JSON.parse(JSON.stringify(s))));
const saved={version:1,money:89850,buildings:[{x:1,y:2,type:'res',variant:0},{x:2,y:2,type:'res',variant:1}]};const migrated=R.restore(saved);assert.equal(migrated.version,2);assert.deepEqual(migrated.buildings,saved.buildings);assert.equal(migrated.money,saved.money);
assert.equal(R.restore({...s,money:100000}),null);assert.equal(R.restore({...s,buildings:[...s.buildings,s.buildings[0]]}),null);
s=R.fresh();q=R.quote(s,'res',p(.7,1.1),p(.7+9*R.spacing,1.1));assert.equal(q.cells.length,10);assert.equal(q.total,50750);assert.deepEqual(q,R.quote(s,'res',p(.7+9*R.spacing,1.1),p(.7,1.1)));
R.build(s,'res',p(.7,1.1),p(.7+9*R.spacing,1.1));assert.equal(s.money,49250);for(let i=0;i<s.buildings.length;i++)for(let j=i+1;j<s.buildings.length;j++)assert(!R.overlaps(s.buildings[i],s.buildings[j]));
const prior=JSON.stringify(s);assert.equal(R.build(s,'ind',p(4,7),p(15,20)),false);assert.equal(JSON.stringify(s),prior);
for(const point of [p(.1,.1),p(31.9,31.9),p(-1,8),p(Infinity,2)])assert.equal(R.quote(R.fresh(),'res',point,point).cells.length,0);
assert.equal(R.quote(R.fresh(),'res',p(.5,.5),p(.5,.5)).cells.length,1);assert.equal(R.quote(R.fresh(),'res',p(31.5,31.5),p(31.5,31.5)).cells.length,1);
console.log('PASS: fractional placement, box collision, neighboring free placement, area packing, reverse drag, budget, bounds, persistence and v1 migration.');
